### ISSUE TITLE
Non-Population of Embeds to past 1 to Forums and Nothing past 3 Embeds will populate

### ISSUE THREAD

**Issue by LarryThiessen** [discohook/discohook#22]
Good Afternoon -

I'm learning [testing] sending Embeds to a Forum today but I've having issues sending more then 1 Embed

* I basically set up a small Embed with 2 basic Embeds to go to a Forum 
> Embed 1 is an image
> Embed 2 is text/button
* I also tried to send the same Embeds with to 2 Different WebHooks: 1 Embed Message to a forum and the second to a text channel

It sends the first one but not the second - its stuck on Sending... for Embed 2 for both examples

Thread ID and Webhooks are correct 

> I'm also finding that I'm not able to populate past 3 Embeds out of 5.  The 4th and 5th Embed just dont populate

Any help would be appreciated

**Comment by shayypy** [comment]
I'm lacking debug info for this one but I saw on discord that you have considered it solved so I'm going to close this issue
