### ISSUE TITLE
Bot Posting Webhook Name above every Embed

### ISSUE THREAD

**Issue by LarryThiessen** [discohook/discohook#24]
Bot Posting Webhook Name above every Embed

![image](https://github.com/user-attachments/assets/12047ada-8312-4a16-bf33-9f8323abc378)

I'm positive this cant be intended because it looks terrible.

**Comment by shayypy** [comment]
I believe this is just how compact mode looks?

**Comment by LarryThiessen** [comment]
> I believe this is just how compact mode looks?

I'm not using Compact Mode - this is a ScreenShot from the DeskTop 

Its posting the Name of the WEBHOOK on Every Embed .. shouldn't do that

**Comment by LarryThiessen** [comment]
Correction it's above Every MESSAGE

**Comment by shayypy** [comment]
I think you should double check your display settings
