### ISSUE TITLE
Scheduling backup tomorrow bug

### ISSUE THREAD

**Issue by dorechen** [discohook/discohook#25]
minimum value verification on the Time TextInput incorrectly thinks that "tomorrow" date is the same day as `now` date
<img width="604" alt="Screenshot 2024-09-11 at 10 05 38 PM" src="https://github.com/user-attachments/assets/3c022dd0-f45d-448a-8e2e-a56d24bbc27f">

**Comment by dorechen** [comment]
the bug is in the "Edit Backup Details" modal, Time TextInput's `min` ternery function. Instead of converting to ISO string and then comparing, you want to just compare the local time 

```
let now = new Date("2024-09-11T22:00:00+12:00") 
let scheduleDate = new Date("2024-09-12T10:00:00+12:00")

// this is what you have at the moment
console.log(scheduleDate.toISOString().split("T")[0] === now.toISOString().split("T")[0])
// true

// this is what you want
console.log(scheduleDate.getDate() == now.getDate() && scheduleDate.getMonth() == now.getMonth() && scheduleDate.getFullYear() == now.getFullYear())
// false

```

**Comment by shayypy** [comment]
Thanks
