### ISSUE TITLE
Color picker omits leading zeros in hex

### ISSUE THREAD

**Issue by iamqw3rty** [discohook/discohook#30]
Attempted to restore an embed for editing, to discover Discohook restored the color hex as `#5029`, when the actual color code is `#005029`. Attached below is embed as it appears in Discord, and embed as it appears in Discohook.
![image](https://github.com/user-attachments/assets/92f48c22-9c0d-43f4-a883-b688f9f39332)
![image](https://github.com/user-attachments/assets/87f518da-70a0-4c0b-929b-7fd5dbb410c3)

![image](https://github.com/user-attachments/assets/63afefdc-716b-46bb-8c8f-4d9c662c919c)
![image](https://github.com/user-attachments/assets/b0911e4e-d18b-4929-8598-7c7a58677ea5)

**Comment by iamqw3rty** [comment]
Okay so after some further experimentation I've discovered it just doesn't let you input certain colors?

https://github.com/user-attachments/assets/eb954098-068b-46f1-96ba-180315ceee09

**Comment by shayypy** [comment]
This is a known bug with the way colors are parsed. Unsure if it's upstream (`react-color`) but thanks for putting it on the issue tracker regardless 👍

**Comment by iamqw3rty** [comment]
boowomp
