### ISSUE TITLE
Selectable window where it shouldn't be a selectable window.

### ISSUE THREAD

**Issue by lev1ordc** [discohook/discohook#31]
You are able to click on the message, where it notifies you that you're editing a backup.
Clicked:
![image](https://github.com/user-attachments/assets/beede782-99ef-46ec-975c-0b8e56614155)
Not Clicked:
![image](https://github.com/user-attachments/assets/e63268a0-b7a5-486d-94dc-19fa3da3b5f3)

**Comment by shayypy** [comment]
https://github.com/user-attachments/assets/2b1f9211-fbcb-49b1-9285-a1b634f8d011
