### ISSUE TITLE
Add support for webhooks that are posting into forum/media channels

### ISSUE THREAD

**Issue by Pixeluted** [discohook/discohook#32]
As of right now, nothing special will pop up when a webhook that posts into forum/media is entered. However discord supports sending messages to already existing posts or creating new posts, as their docs say 

"If the webhook channel is a forum or media channel, you must provide either thread_id in the query string params, or thread_name in the JSON/form params. If thread_id is provided, the message will send in that thread. If thread_name is provided, a thread with that name will be created in the channel." (In https://discord.com/developers/docs/resources/webhook#execute-webhook)

Would be really useful for people making info forum posts so they can do embeds without any external bot.

**Comment by shayypy** [comment]
This is already supported with the forum thread name box https://discohook.app/guide/getting-started/threads
