### ISSUE TITLE
No webhook found 

### ISSUE THREAD

**Issue by arfizato** [discohook/discohook#33]
Trying to reuse a previously used webhook (even if created by discohook.app) on the app is impossible without the webhook URL:
![image](https://github.com/user-attachments/assets/8665b2f0-043c-4de5-b0b0-abc386995b38)

![image](https://github.com/user-attachments/assets/db34a50a-326e-4e04-b731-30104fa2cda0)

### Steps to recreate

- Create webhook send any message.
- refresh the page 
- try to find the previously used webhook
- won't work

**Comment by The-User-1** [comment]
# Interactional Buttons and Context Menu Commands Won't Work
it will always say "this interaction failed"

**Comment by shayypy** [comment]
You can reuse bot-owned webhooks either by selecting them in the list after selecting your server (the menu in screenshot 1) or with bot commands (/webhook info). The disabled copy URL button is a Discord feature and I cannot enable it.
