### ISSUE TITLE
IN {member.role_ids} ALWAYS FAILS.

### ISSUE THREAD

**Issue by LosokosG** [discohook/discohook#34]
I have an issue with my flow that is supposed to check for roles a user has on the server.

![photo](https://github.com/user-attachments/assets/13e104b7-6b75-4dc5-ae10-a87fc292a1dd)

The bot is higher in the role list than the ones i am checking for, the flow always fails no matter what i try.

I tried to switch places of these. Didn't work
![switch](https://github.com/user-attachments/assets/67307b29-d339-44be-8087-e01fe656fea4)

I tried doing `{member.role_ids}` instead of `member.role_ids`. Did not work.

![memberroles](https://github.com/user-attachments/assets/e026f0d8-4830-4b1f-b5f8-514647fd34a1)

I have these roles and their ID's are 100% correct in the flow:
![roles](https://github.com/user-attachments/assets/8fab8a14-1b06-4887-8031-e97f9f335752)

When i click on the button i ALWAYS get this:
![button](https://github.com/user-attachments/assets/2978c0b2-cedc-4c38-b770-159cef940cb2)
Doesn't matter whether i have these roles or not.

The flow is a bit longer but i need to fix the issue here.

Here is my entire flow:
```
 "components": [
    {
      "type": 1,
      "components": [
        {
          "style": 3,
          "type": 2,
          "label": "Start Trial",
          "emoji": {
            "id": "1301922423830220891",
            "name": "VipGif",
            "animated": true
          },
          "flowId": "99814861780815884",
          "custom_id": "p_99647404801789956",
          "flow": {
            "name": null,
            "actions": [
              {
                "type": 2,
                "function": {
                  "type": 4,
                  "element": {
                    "varType": 0,
                    "value": "{member.role_ids}"
                  },
                  "array": {
                    "value": "[\"1302034000654897152\", \"1292928125365129288\"]",
                    "varType": 0
                  }
                },
                "then": [
                  {
                    "type": 11,
                    "message": {
                      "content": "You are verified and have rules accepted",
                      "flags": 64
                    }
                  }
                ],
                "else": [
                  {
                    "type": 11,
                    "message": {
                      "content": "You need to accept the rules and verify.\n{member.mention}",
                      "flags": 64
                    }
                  }
                ]
              },
              {
                "type": 2,
                "function": {
                  "type": 3,
                  "conditions": [
                    {
                      "type": 4,
                      "element": {
                        "value": "member.role_ids"
                      },
                      "array": {
                        "value": "[\"1302012795063111701\"]"
                      }
                    }
                  ]
                },
                "then": [
                  {
                    "type": 11,
                    "message": {
                      "content": "You've already used your free trial.",
                      "flags": 64
                    }
                  }
                ],
                "else": [
                  {
                    "type": 3,
                    "roleId": "1302001858159837184"
                  },
                  {
                    "type": 3,
                    "roleId": "1302012795063111701"
                  },
                  {
                    "type": 11,
                    "message": {
                      "content": "TRIAL HAS STARTED",
                      "flags": 64
                    }
                  }
                ]
              }
            ]
          }
        }
      ]
```
      
      
I am guessing it is with my formatting or something with logic, i really hope it's a problem on my end and not the devs...
      
Please help me out!!!

**Comment by shayypy** [comment]
1. You're checking if an array is inside another array. I'm sure you want to check if any of the array elements overlap, but that's not something you can do with just one check function right now
2. You are checking if the literal string `"member.role_ids"` is inside of the array of role IDs (you forgot to mark the attribute reference as [mirror](https://discohook.app/guide/recipes/checks))

**Comment by The-User-1** [comment]
its because you need to pull out a single value from the variable(array)
but i dont know how
